%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 423.13912392  # 957.994 
Camera.fy: 564.14094594  #  955.3280
Camera.cx: 319.11230866   # 790.335
Camera.cy: 243.02423317  #   250.6631

Camera.k1: -0.02780888
Camera.k2: -0.09766579
Camera.p1: 0.00070702
Camera.p2: -0.00084053
Camera.k3: 0
#1520 568
Camera.width: 640
Camera.height: 480
# Deptmap values factor
DepthMapFactor: 504
Camera.bf: 40.0

Rect.x: 40
Rect.y: 40
Rect.width: 560
Rect.height: 400

